### ISSUE TITLE
Ocicats Review (1) 🐈 

### ISSUE THREAD

**Issue by aldemeery** [MarilenaRoque/newsWeek-bootstrap#1]
# Ocicats Review (1) 🐈 
###### A code review by the standup team at Microverse

---

### Way to go 👏🏻

- [x] ✔ Excellent job with the navbar that shows up when scrolling 👌 
- [x] ✔ Well done using CSS variables.
- [x] ✔ Very good use of bootstrap classes.

### We think you need to 🤓

- [ ] 💀 Make all the paths relative, so they work on the live demo.
- [ ] 💀 Fix the W3Validator issues.
- [ ] ⚠ Add some padding to the footer.

**Comment by MarilenaRoque** [comment]
Thank you so much for the review team!!! :cat2:

**I have fixed all the issues listed:**
- [X] Make all the paths relative, so they work on the live demo.
- [X] Fix the W3Validator issues.
- [X] Add some padding to the footer.

**Additionally:**
- Added the border in the footer
